# This file was generated by GoReleaser. DO NOT EDIT.
cask "onda" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "263c0e839ec2bdadf4a2a5a8bb7e1e7c5609c719c7d7546b81685858d7453de9"
      url "https://github.com/pedrosousa13/onda/releases/download/v#{version}/onda_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a4ad58aa30d158073385b576b70d03e4b4ad0a9858fb695e5a30c259195a0fe9"
      url "https://github.com/pedrosousa13/onda/releases/download/v#{version}/onda_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7e513141b2a66c2854439c16bc8792392f6c514450a0dbc2a60fb308de70f97a"
      url "https://github.com/pedrosousa13/onda/releases/download/v#{version}/onda_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2f01e147e230cf7193251e7c3ddb884a935b1a0b1a7eaa82b518473ee4130084"
      url "https://github.com/pedrosousa13/onda/releases/download/v#{version}/onda_#{version}_linux_arm64.tar.gz"
    end
  end

  name "onda"
  desc "Ethical, privacy-minded radios-of-the-world TUI"
  homepage "https://github.com/pedrosousa13/onda"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "mpv",
    ]

  binary "onda"

  postflight do
    if OS.mac? && File.exist?("#{staged_path}/onda")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/onda"]
    end
  end

  # No zap stanza required

end
