# This file was generated by GoReleaser. DO NOT EDIT.
cask "onda" do
  version "1.6.1"

  on_macos do
    on_intel do
      sha256 "19a8f2038711200d3ae35667fab0be290c5c1002e2194c492420ae02cf24ed63"
      url "https://github.com/pedrosousa13/onda/releases/download/v#{version}/onda_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1efac8bfd1f530cd241d8a3d09b0aa702885db4b8138abe67debcc2765751e36"
      url "https://github.com/pedrosousa13/onda/releases/download/v#{version}/onda_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "87d2f2a4a0a34e5900f6be842dbe0cff817f6f431cd9757e6c8a6af102e73968"
      url "https://github.com/pedrosousa13/onda/releases/download/v#{version}/onda_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d3f5c8ff0db0939d14b2ae2a2e04e58a8ede1517b2fb49b96cc4c517464436a0"
      url "https://github.com/pedrosousa13/onda/releases/download/v#{version}/onda_#{version}_linux_arm64.tar.gz"
    end
  end

  name "onda"
  desc "Ethical, privacy-minded radios-of-the-world TUI"
  homepage "https://github.com/pedrosousa13/onda"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "mpv",
    ]

  binary "onda"

  postflight do
    if OS.mac? && File.exist?("#{staged_path}/onda")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/onda"]
    end
  end

  # No zap stanza required

end
