# This file was generated by GoReleaser. DO NOT EDIT.
cask "onda" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "8db834d931102da4848c6f5fdbf8fe8bc956c32685bb4203da9fdb29b6ef475a"
      url "https://github.com/pedrosousa13/onda/releases/download/v#{version}/onda_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "033ca13d4348192406cd23f67e08682aff40471ff0b1c923059d1052235611bc"
      url "https://github.com/pedrosousa13/onda/releases/download/v#{version}/onda_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d7cf256bb6a8201e36e293fe51bc3b33fac89b5c28b9c3af2feaae27132a11f5"
      url "https://github.com/pedrosousa13/onda/releases/download/v#{version}/onda_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4dded9cc3eafea1ce39aa61ac3f50d106c62727ad1ba662ae50dc8e65bb7099a"
      url "https://github.com/pedrosousa13/onda/releases/download/v#{version}/onda_#{version}_linux_arm64.tar.gz"
    end
  end

  name "onda"
  desc "Ethical, privacy-minded radios-of-the-world TUI"
  homepage "https://github.com/pedrosousa13/onda"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "mpv",
    ]

  binary "onda"

  postflight do
    if OS.mac? && File.exist?("#{staged_path}/onda")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/onda"]
    end
  end

  # No zap stanza required

end
